-- Campaigns table — one row per campaign draft generated by the Campaign Agent
CREATE TABLE IF NOT EXISTS campaigns (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  lead_id     UUID REFERENCES leads(id) ON DELETE CASCADE,
  subject     TEXT NOT NULL,
  email_body  TEXT NOT NULL,
  image_url   TEXT,
  status      TEXT DEFAULT 'pending'
              CHECK (status IN ('pending', 'approved', 'rejected', 'sent')),
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ,
  sent_at     TIMESTAMPTZ
);

-- Index for fast queue queries
CREATE INDEX IF NOT EXISTS campaigns_status_idx ON campaigns(status);
CREATE INDEX IF NOT EXISTS campaigns_lead_id_idx ON campaigns(lead_id);

-- Supabase storage bucket for campaign images (run once)
INSERT INTO storage.buckets (id, name, public)
VALUES ('campaign-images', 'campaign-images', true)
ON CONFLICT (id) DO NOTHING;
